[package]
name = "rust-htslib"
version = "0.22.1-alpha.0"
authors = ["Christopher Schröder <christopher.schroeder@tu-dortmund.de>", "Johannes Köster <johannes.koester@tu-dortmund.de>"]
build = "build.rs"
description = "This library provides HTSlib bindings and a high level Rust API for reading and writing BAM files."
readme = "README.md"
keywords = ["htslib", "bam", "bioinformatics", "pileup", "sequencing"]
license = "MIT"
repository = "https://github.com/rust-bio/rust-htslib.git"
documentation = "https://docs.rs/rust-htslib"


[dependencies]
libc = "0.2"
libz-sys = "1.0"
bzip2-sys = { version = "0.1.6", git = "https://github.com/alexcrichton/bzip2-rs.git", optional = true }
lzma-sys = { version = "0.1.10", optional = true }
itertools = "0.6"
quick-error = "1.2"
newtype_derive = "0.1"
custom_derive = "0.1"
url = "1.4"
ieee754 = "0.2"
lazy_static = "0.2"
bitflags = "0.9"
regex = "1.0"
linear-map = "1.2.0"
serde = { version = "^1", optional = true }
bio-types = ">=0.1.1"

[features]
default = ["bzip2", "lzma"]
bzip2 = ["bzip2-sys"]
lzma = ["lzma-sys"]

[dev-dependencies]
tempdir = "0.3"
bincode = "1.0"
serde_json = "1.0"
pretty_assertions = "0.5.1"

[build-dependencies]
fs-utils = "1.0"
bindgen = "0.36"
cc = "1.0"
